spring:
  datasource:
    url: jdbc:mysql://localhost:3306/helloworld?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    encoding: UTF-8
    mode: HTML5
    cache: false
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: teach.entity

server:
  port: 8080